on:
  push:
    branches:
      - master
  workflow_dispatch:

name: Deploy to Amazon ECS

jobs:
  build:
    uses:
      ucdavis-lsit/actions/.github/workflows/deploy.yml@main
    with:
      repo: 'aggie-bot-staging'
      cluster: 'legacy'
      service: 'aggie-bot-staging'
    secrets:
      access-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      secret-key: $${{ secrets.AWS_SECRET_ACCESS_KEY }}